name: Sync to Hugging Face Space
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab 
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: false
          
      - name: Ignore large files
        run : git filter-branch --index-filter 'git rm -rf --cached --ignore-unmatch "Rag_Documents/layout-parser-paper.pdf"' HEAD

      - name: Push to Hugging Face Hub
        run: |
            git config --global user.email "aniketec2014@gmail.com"
            git config --global user.name "Aniket261992"
            git remote set-url origin https://Aniket2692:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Aniket2692/SDLC_Agentic_Workflow
            git push --force origin main